apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
__RESOURCES__
namespace: sonataflow-infra

configurations:
- config/image-configuration.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - envs:
      - secret.properties
    name: thesting12345-secret
configMapGenerator:
  - envs:
      - config.properties
    name: thesting12345-gitops

# Replace dev profile in SonataFlow instance(s), add image and envFrom
patches:
- path: sonataflow-patch.yaml
  target:
    kind: SonataFlow
    name: thesting12345
images:
- name: serverless-workflow-thesting12345
  newName: quay.io/orchestrator-test/foo
  newTag: __IMAGE_TAG__
